---
title: Litter decomposability traits as a tool for plant invasion in an urban environment of north-western Siwalik region, India

abstract: 

authors:
    - admin
    - Meenu Patil
    - Pardeep Kumar
    - Anand Narain Singh
    
event: "23rd Punjab Science Congress"

event_url:

location: Sant Longowal Institute of Engineering and Technology (SLIET)

address:
  street: SLIET Road, Longowal   
  city: Sangrur
  postcode: "148106"
  country: India
  
all_day: false

date: "2020-02-07T10:00:00Z"

date_end: "2020-02-09T17:00:00Z"


featured: false

image:
  caption: 'Image credit: [**Unsplash**](https://unsplash.com/photos/bzdhc5b3Bxs)'
  focal_point: Right
  
links:
- icon: twitter
  icon_pack: fab
  name: Follow
  url: https://twitter.com/abkumar_
  


projects:
- internal-project

publishDate: "2017-01-01T00:00:00Z"

slides: 

summary: "Oral presentation at SLIET, Longowal. Abstract ID: YAP-02. 49 p."

tags:
    - Litter decomposition
    - Siwalik

url_code: ""

url_pdf: ""

url_slides: ""

url_video: ""
---

Urban ecosystems of many tropics in the world often serve as the reservoir of exotic plants due to intentional introduction for ornamental and horticultural purposes. It is likely that some of these plants may escape their site of introduction and become invasive in the adjacent forest patches. Such plants can potentially modify important ecosystem functions like cycling of nutrients by adjusting their decomposition rates, which in turn may facilitate their increased abundance in the invaded ecosystem. In order to test this hypothesis, we investigated the decomposition rates of five native and five exotic (three invasive and two non-invasive) species by litter bag experiment for a single year. Results indicated that invasive exotic species exhibited a higher rate of decomposition, whereas, non-invasive exotic species exhibited slower rates as compared to native species. However, present study did not find any significant differences in overall decomposition rates of native and exotic species but these rates were significantly correlated with physical traits of the initial litter. Interestingly, specific leaf area of initial litter was a good predictor for decomposition rates in the present study. Our study confirms that invasive exotic plants oriented to maintain a higher grade of physical quality of litter than native and non-invasive exotic species which promotes their faster decomposition in the urban ecosystems. In conclusion, a higher decomposition rate possibly due to better physical quality of litter may facilitate the naturalisation and invasion of exotic plants irrespective of their origin.
